// <auto-generated />
using System;
using Infrastructure.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastracture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712120406_yys")]
    partial class yys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Contract", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Contracts");
            });

            modelBuilder.Entity("Domain.Entities.Document", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("DocumentType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("IdModelDocuments")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("document_type")
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnType("nvarchar(21)");

                b.HasKey("Id");

                b.ToTable("Documents");

                b.HasDiscriminator<string>("document_type").HasValue("Document");

                b.UseTphMappingStrategy();
            });

            modelBuilder.Entity("Domain.Entities.ModelDocument", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("ModeleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("NomModele")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ModelDocuments");
            });

            modelBuilder.Entity("Domain.Entities.Report", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CheminFichier")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DateCreation")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("NomRapport")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RapportId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Reports");
            });

            modelBuilder.Entity("Domain.Entities.Request", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("DocumentStatus")
                    .HasColumnType("int");

                b.Property<string>("DocumentType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("IdTrainee")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("ModeleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("NameTrainee")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ReasonRejection")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("Requests");

                b.HasData(
                    new
                    {
                        Id = new Guid("72e2e924-8cdc-4074-8ada-cfe8fbff7456"),
                        CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        DocumentStatus = 1,
                        DocumentType = "document_trainee",
                        IdTrainee = new Guid("dcd3d448-7d87-4e28-92a9-d367cfb9c27d"),
                        ModeleId = new Guid("afcda754-75e3-43d4-a698-239452a8044b"),
                        ReasonRejection = "",
                        Role = "assistant"
                    },
                    new
                    {
                        Id = new Guid("292fbbc1-6875-44f9-a0ed-8fd3613d1fff"),
                        CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        DocumentStatus = 2,
                        DocumentType = "document_traineeList",
                        IdTrainee = new Guid("048e2f4a-46c1-4e24-bb05-d35f13824074"),
                        ModeleId = new Guid("c8a43031-3bac-41f6-ac0e-526a33ac4096"),
                        ReasonRejection = "ya pas de justification",
                        Role = "director"
                    });
            });

            modelBuilder.Entity("Domain.Entities.RequestInternship", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModifiedDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("RequestInternships");
            });

            modelBuilder.Entity("Domain.Entities.DocumentTrainee", b =>
            {
                b.HasBaseType("Domain.Entities.Document");

                b.Property<Guid>("IdTrainee")
                    .HasColumnType("uniqueidentifier");

                b.HasDiscriminator().HasValue("document_trainee");
            });

            modelBuilder.Entity("Domain.Entities.DocumentTraineeList", b =>
            {
                b.HasBaseType("Domain.Entities.Document");

                b.Property<string>("IdTraineesList")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasDiscriminator().HasValue("document_traineeList");
            });
#pragma warning restore 612, 618
        }
    }
}